services:
  redis:
    image: 'redis:latest'
    container_name: celery-polaroid-redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'

  worker:
    image: celery-polaroid
    volumes:
      - .:/app
    depends_on:
      - redis
      - scheduler
    env_file:
      - .env
    environment:
      - instance=worker
    entrypoint: [ './entrypoint.sh', 'worker' ]

  monitoring:
    image: celery-polaroid
    container_name: celery-polaroid-monitoring
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - instance=monitoring
    env_file:
      - .env
    entrypoint: ['./entrypoint.sh', 'monitoring']

  scheduler:
    build: .
    image: celery-polaroid
    container_name: celery-polaroid-scheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - instance=scheduler
    env_file:
      - .env
    entrypoint: ['./entrypoint.sh', 'scheduler']
